{% set name = "robocrys" %}
{% set version = "0.2.12" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robocrys-{{ version }}.tar.gz
  sha256: 424200ff6d75ebda16e3d1c379ff0a1c6e3c4c814fc14cc05a0098cccde2b42c

build:
  number: 0
  noarch: python
  entry_points:
    - robocrys = robocrys.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - ruamel.yaml
    - inflect
    - matminer >=0.9.2
    - monty
    - networkx
    - numpy
    - pubchempy
    - pybtex
    - pymatgen >=2024.1.26
    - python >={{ python_min }}
    - scipy
    - spglib >=2.5.0
    - mp-api

test:
  requires:
    - python {{ python_min }}
  imports:
    - robocrys
    - robocrys.condense
  commands:
    - robocrys --help

about:
  home: https://github.com/hackingmaterials/robocrystallographer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic generation of crystal structure descriptions.
  description: |
    Robocrystallographer is a tool to generate text descriptions of
    crystal structures. Similar to how a real-life crystallographer
    would analyse a structure, robocrystallographer looks at the
    symmetry, local environment, and extended connectivity when
    generating a description. The package includes utilities for
    identifying molecule names, component orientations, heterostructure
    information, and more...
  doc_url: https://hackingmaterials.lbl.gov/robocrystallographer/
  dev_url: https://github.com/hackingmaterials/robocrystallographer

extra:
  recipe-maintainers:
    - jan-janssen
