{% set name = "robocrys" %}
{% set version = "0.2.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robocrys-{{ version }}.tar.gz
  sha256: 6ca56df390dc312e4cb8fafcc1d9a5e132bcefd2b62cb2bbe007c13e7206d2bc

build:
  number: 0
  noarch: python
  entry_points:
    - robocrys = robocrys.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ruamel.yaml
    - inflect
    - matminer >=0.9.2
    - monty
    - networkx
    - numpy
    - pubchempy
    - pybtex
    - pymatgen >=2024.1.26
    - python >=3.6
    - scipy
    - spglib >=2.5.0
    - mp-api

test:
  imports:
    - robocrys
    - robocrys.condense
  commands:
    - pip check
    - robocrys --help
  requires:
    - pip

about:
  home: https://github.com/hackingmaterials/robocrystallographer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic generation of crystal structure descriptions.
  description: |
    Robocrystallographer is a tool to generate text descriptions of
    crystal structures. Similar to how a real-life crystallographer
    would analyse a structure, robocrystallographer looks at the
    symmetry, local environment, and extended connectivity when
    generating a description. The package includes utilities for
    identifying molecule names, component orientations, heterostructure
    information, and more...
  doc_url: https://hackingmaterials.lbl.gov/robocrystallographer/
  dev_url: https://github.com/hackingmaterials/robocrystallographer

extra:
  recipe-maintainers:
    - jan-janssen
