schema_version: 1

context:
  name: robocrys
  version: "0.2.13"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/robocrys-${{ version }}.tar.gz
  sha256: 8c52770d37d9e241e1f73ef6a9ad93e3070b1d0fa252aa8377f15bd0485d5719

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - robocrys = robocrys.cli:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - ruamel.yaml
    - inflect
    - matminer >=0.10.0
    - monty
    - networkx
    - numpy
    - pubchempy
    - pybtex
    - pymatgen >=2024.1.26
    - python >=${{ python_min }}
    - scipy >=1.17.0
    - spglib >=2.5.0
    - mp-api

tests:
  - python:
      imports:
        - robocrys
        - robocrys.condense
      pip_check: false
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - robocrys --help

about:
  license: MIT
  license_file: LICENSE
  summary: Automatic generation of crystal structure descriptions.
  description: |
    Robocrystallographer is a tool to generate text descriptions of
    crystal structures. Similar to how a real-life crystallographer
    would analyse a structure, robocrystallographer looks at the
    symmetry, local environment, and extended connectivity when
    generating a description. The package includes utilities for
    identifying molecule names, component orientations, heterostructure
    information, and more...
  homepage: https://github.com/hackingmaterials/robocrystallographer
  repository: https://github.com/hackingmaterials/robocrystallographer
  documentation: https://hackingmaterials.lbl.gov/robocrystallographer/

extra:
  recipe-maintainers:
    - jan-janssen
